app = 'teste-tecnico'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'